### ISSUE TITLE
Migrar Converter de java8 para java6

### ISSUE THREAD

**Issue by ericdallo** [alexandregama/correios-tracking-java-sdk#26]
# Goal

Para maior acessibilidade do SDK, migrar para java 1.6

**Comment by alexandregama** [comment]
Faz todo sentido! :)

On Fri, Jun 17, 2016 at 10:21 AM, Eric Dallo <notifications@github.com>
wrote:

> Goal
>
> Para maior acessibilidade do SDK, migrar para java 1.6
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexandregama/correios-tracking-java-sdk/issues/26>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAaHBOzf66R1am0nzIrhcFUupq8LCQf0ks5qMp9tgaJpZM4I4We5>
> .
>



-- 

Alexandre Gama

@alexandregamma <http://twitter.com/alexandregamma>
www.caelum.com.br
www.elo7.com.br
*about.me/alexandregama <http://about.me/alexandregama>*
alexandregama.org
